name: ForwardMarsh
favicon: null
layout_spectrum: 0.74926
typography_spectrum: 0.3424008737783879
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5486273977439851
  lightness: 0.9282570844516158
  saturation: 0.12320155091583729
  rhythmicContrast: 0.4826051767449826
purpose: []
